version: 2.1 # use CircleCI 2.0
orbs: 
    snyk: snyk/snyk@1.1.2
jobs: # a collection of steps
  build-and-test: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/nodejs-goof # directory where steps will run
    docker: # run the steps with Docker
      - image: cimg/node:lts # ...with this image as the primary container; this is where all `steps` will run, old base image was deprecated
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-snyk
          command: 'sudo npm install -g snyk'     
      - run: # run snyk help - test snyk is installed and working
          name: snyk-help
          command: snyk --help
      - run:
          name: install-snyk-to-html
          command: 'sudo npm install snyk-to-html -g'        
      - run: # run snyk auth - authenticate snyk use environment variables to add token
          name: snyk auth
          command: snyk auth $SNYK_TOKEN
      - run: # run snyk test - run snyk test and only fail build for critical issues
          name: snyk test
          command: snyk test --severity-threshold=critical --json-file-output=open-source-results.json || true
      - run:
          name: generate HTML report for open-source
          command: cat open-source-results.json | snyk-to-html -o open-source-results.html
      - store_artifacts:
          path: open-source-results.html          
      - run: # run snyk monitor - run snyk monitor
          name: snyk monitor
          command: snyk monitor
      - run: # run snyk code test
          name: snyk code test
          command: snyk code test --severity-threshold=high --json-file-output=code-results.json || true
      - run: # generate html for code TEST
          name: generate HTML report for code
          command: cat code-results.json | snyk-to-html -o code-results.html
      - store_artifacts:
          path: code-results.html
workflows:
  snyk-build-and-test:
    jobs:
      - build-and-test
